# Generated by Django 5.1.7 on 2025-03-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Date of publication')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
        ),
    ]
