# Generated by Django 5.2 on 2025-05-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Name')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Date of publication')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Picture')),
                ('quote', models.TextField(blank=True, verbose_name='Quote')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book')),
            ],
        ),
    ]
