# Generated by Django 5.1.7 on 2025-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Picture'),
        ),
    ]
