# Generated by Django 5.1.7 on 2025-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quote',
            field=models.TextField(blank=True, verbose_name='Quote'),
        ),
    ]
